// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/DBrange/didis-comp-bk/domains/user/ports/drivens (interfaces: ForQueryingUser)
//
// Generated by this command:
//
//	mockgen -destination=tests/mocks/mock_for_querying_user.go -package=mocks github.com/DBrange/didis-comp-bk/domains/user/ports/drivens ForQueryingUser
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/DBrange/didis-comp-bk/domains/user/models/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockForQueryingUser is a mock of ForQueryingUser interface.
type MockForQueryingUser struct {
	ctrl     *gomock.Controller
	recorder *MockForQueryingUserMockRecorder
}

// MockForQueryingUserMockRecorder is the mock recorder for MockForQueryingUser.
type MockForQueryingUserMockRecorder struct {
	mock *MockForQueryingUser
}

// NewMockForQueryingUser creates a new mock instance.
func NewMockForQueryingUser(ctrl *gomock.Controller) *MockForQueryingUser {
	mock := &MockForQueryingUser{ctrl: ctrl}
	mock.recorder = &MockForQueryingUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForQueryingUser) EXPECT() *MockForQueryingUserMockRecorder {
	return m.recorder
}

// RegisterUser mocks base method.
func (m *MockForQueryingUser) RegisterUser(arg0 context.Context, arg1 *dto.RegisterUserDTOReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockForQueryingUserMockRecorder) RegisterUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockForQueryingUser)(nil).RegisterUser), arg0, arg1)
}
