version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: didis-comp-bk
    command: mongod --auth

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-api
    restart: on-failure
    volumes:
      - .:/go/src/api
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://admin:password@mongo:27017/didis-comp-bk?authSource=admin
    depends_on:
      - mongo

volumes:
  mongo_data:
    driver: local

networks:
  default:
    name: my-network