package models

type AVAILABILITY_STATUS string

const (
	AVAILABILITY_STATUS_AVAILABLE          AVAILABILITY_STATUS = "AVAILABLE"
	AVAILABILITY_STATUS_NOT_AVAILABLE      AVAILABILITY_STATUS = "NOT_AVAILABLE"
	AVAILABILITY_STATUS_POSSIBLY_AVAILABLE AVAILABILITY_STATUS = "POSSIBLY_AVAILABLE"
)

func (as AVAILABILITY_STATUS) IsValid() bool {
	switch as {
	case AVAILABILITY_STATUS_AVAILABLE, AVAILABILITY_STATUS_NOT_AVAILABLE, AVAILABILITY_STATUS_POSSIBLY_AVAILABLE:
		return true
	}
	return false
}
