package models

type TOURNAMENT_MATCHES_CAPACITY int

const (
	TOURNAMENT_MATCHES_CAPACITY_ONE   TOURNAMENT_MATCHES_CAPACITY = 1
	TOURNAMENT_MATCHES_CAPACITY_TWO   TOURNAMENT_MATCHES_CAPACITY = 2
	TOURNAMENT_MATCHES_CAPACITY_THREE TOURNAMENT_MATCHES_CAPACITY = 4
	TOURNAMENT_MATCHES_CAPACITY_FOUR  TOURNAMENT_MATCHES_CAPACITY = 8
	TOURNAMENT_MATCHES_CAPACITY_FIVE  TOURNAMENT_MATCHES_CAPACITY = 16
	TOURNAMENT_MATCHES_CAPACITY_SIX   TOURNAMENT_MATCHES_CAPACITY = 32
	TOURNAMENT_MATCHES_CAPACITY_SEVEN TOURNAMENT_MATCHES_CAPACITY = 64
	TOURNAMENT_MATCHES_CAPACITY_EIGHT TOURNAMENT_MATCHES_CAPACITY = 128
	TOURNAMENT_MATCHES_CAPACITY_NINE  TOURNAMENT_MATCHES_CAPACITY = 256
)

var validMatchesCapacities = map[TOURNAMENT_MATCHES_CAPACITY]bool{
	TOURNAMENT_MATCHES_CAPACITY_ONE:   true,
	TOURNAMENT_MATCHES_CAPACITY_TWO:   true,
	TOURNAMENT_MATCHES_CAPACITY_THREE: true,
	TOURNAMENT_MATCHES_CAPACITY_FOUR:  true,
	TOURNAMENT_MATCHES_CAPACITY_FIVE:  true,
	TOURNAMENT_MATCHES_CAPACITY_SIX:   true,
	TOURNAMENT_MATCHES_CAPACITY_SEVEN: true,
	TOURNAMENT_MATCHES_CAPACITY_EIGHT: true,
	TOURNAMENT_MATCHES_CAPACITY_NINE:  true,
}

func (tmc TOURNAMENT_MATCHES_CAPACITY) IsValid() bool {
	_, ok := validMatchesCapacities[tmc]
	return ok
}

var ALL_TOURNAMENT_MATCHES_CAPACITY = []TOURNAMENT_MATCHES_CAPACITY{
	TOURNAMENT_MATCHES_CAPACITY_ONE,
	TOURNAMENT_MATCHES_CAPACITY_TWO,
	TOURNAMENT_MATCHES_CAPACITY_THREE,
	TOURNAMENT_MATCHES_CAPACITY_FOUR,
	TOURNAMENT_MATCHES_CAPACITY_FIVE,
	TOURNAMENT_MATCHES_CAPACITY_SIX,
	TOURNAMENT_MATCHES_CAPACITY_SEVEN,
	TOURNAMENT_MATCHES_CAPACITY_EIGHT,
	TOURNAMENT_MATCHES_CAPACITY_NINE,
}