package models

type TOURNAMENT_CAPACITY int

const (
	TOURNAMENT_CAPACITY_ONE   TOURNAMENT_CAPACITY = 2
	TOURNAMENT_CAPACITY_TWO   TOURNAMENT_CAPACITY = 4
	TOURNAMENT_CAPACITY_THREE TOURNAMENT_CAPACITY = 8
	TOURNAMENT_CAPACITY_FOUR  TOURNAMENT_CAPACITY = 16
	TOURNAMENT_CAPACITY_FIVE  TOURNAMENT_CAPACITY = 32
	TOURNAMENT_CAPACITY_SIX   TOURNAMENT_CAPACITY = 64
	TOURNAMENT_CAPACITY_SEVEN TOURNAMENT_CAPACITY = 128
	TOURNAMENT_CAPACITY_EIGHT TOURNAMENT_CAPACITY = 256
	TOURNAMENT_CAPACITY_NINE  TOURNAMENT_CAPACITY = 512
)

var validCapacities = map[TOURNAMENT_CAPACITY]bool{
	TOURNAMENT_CAPACITY_ONE:   true,
	TOURNAMENT_CAPACITY_TWO:   true,
	TOURNAMENT_CAPACITY_THREE: true,
	TOURNAMENT_CAPACITY_FOUR:  true,
	TOURNAMENT_CAPACITY_FIVE:  true,
	TOURNAMENT_CAPACITY_SIX:   true,
	TOURNAMENT_CAPACITY_SEVEN: true,
	TOURNAMENT_CAPACITY_EIGHT: true,
	TOURNAMENT_CAPACITY_NINE:  true,
}

func (tc TOURNAMENT_CAPACITY) IsValid() bool {
	_, ok := validCapacities[tc]
	return ok
}

func IsValidTournamentCapacity(num int) bool {
	for _, capacity := range ALL_TOURNAMENT_CAPACITY {
		if int(capacity) == num {
			return true
		}
	}
	return false
}

var ALL_TOURNAMENT_CAPACITY = []TOURNAMENT_CAPACITY{
	TOURNAMENT_CAPACITY_ONE,
	TOURNAMENT_CAPACITY_TWO,
	TOURNAMENT_CAPACITY_THREE,
	TOURNAMENT_CAPACITY_FOUR,
	TOURNAMENT_CAPACITY_FIVE,
	TOURNAMENT_CAPACITY_SIX,
	TOURNAMENT_CAPACITY_SEVEN,
	TOURNAMENT_CAPACITY_EIGHT,
	TOURNAMENT_CAPACITY_NINE,
}


